#include "operator.h"

const char *operator_to_str(Operator op) {
   switch (op) {
   case OP_PLUS:
      return "+";
   case OP_MINUS:
      return "-";
   case OP_STAR:
      return "*";
   case OP_SLASH:
      return "/";
   case OP_PERCENT:
      return "%";
   case OP_BANG:
      return "!";
   case OP_AMPERSAND:
      return "&";
   case OP_PIPE:
      return "|";
   case OP_UP_CARET:
      return "^";
   case OP_DOUBLE_LCHEVRON:
      return "<<";
   case OP_DOUBLE_RCHEVRON:
      return ">>";
   case OP_PLUS_EQUAL:
      return "+=";
   case OP_MINUS_EQUAL:
      return "-=";
   case OP_STAR_EQUAL:
      return "*=";
   case OP_SLASH_EQUAL:
      return "/=";
   case OP_PERCENT_EQUAL:
      return "%=";
   case OP_BANG_EQUAL:
      return "!=";
   case OP_AMPERSAND_EQUAL:
      return "&=";
   case OP_PIPE_EQUAL:
      return "|=";
   case OP_UP_CARET_EQUAL:
      return "^=";
   case OP_DOUBLE_LCHEVRON_EQUAL:
      return "<<=";
   case OP_DOUBLE_RCHEVRON_EQUAL:
      return ">>=";
   case OP_LBRACKET:
      return "[";
   case OP_RBRACKET:
      return "]";
   case OP_LPAREN:
      return "(";
   case OP_RPAREN:
      return ")";
   case OP_LBRACE:
      return "{";
   case OP_RBRACE:
      return "}";
   case OP_DOUBLE_AMPERSAND:
      return "&&";
   case OP_DOUBLE_PIPE:
      return "||";
   case OP_LCHEVRON:
      return "<";
   case OP_RCHEVRON:
      return ">";
   case OP_LCHEVRON_EQUAL:
      return "<=";
   case OP_RCHEVRON_EQUAL:
      return ">=";
   case OP_EQUAL_EQUAL:
      return "==";
   case OP_EQUAL:
      return "=";
   case OP_TILDE:
      return "~";
   case OP_INCREMENT:
      return "++";
   case OP_DECREMENT:
      return "--";
   case OP_COMMA:
      return ",";
   case OP_QUESTION:
      return "?";
   case OP_COLON:
      return ":";
   case OP_SEMICOLON:
      return ";";
   case OP_ARROW:
      return "->";
   case OP_DOT:
      return ".";
   case OP_ELIPSES:
      return "...";
   case OP_HASH:
      return "#";
   case OP_DOUBLE_HASH:
      return "##";
   case OP_SIZEOF:
      return "sizeof";
   default:
      return "???";
   }
}
