#ifndef FOX_OPERATOR_H_
#define FOX_OPERATOR_H_

typedef enum {
   OP_PLUS,
   OP_MINUS,
   OP_STAR,
   OP_SLASH,
   OP_PERCENT,
   OP_BANG,
   OP_AMPERSAND,
   OP_PIPE,
   OP_UP_CARET,
   OP_DOUBLE_LCHEVRON,
   OP_DOUBLE_RCHEVRON,
   OP_PLUS_EQUAL,
   OP_MINUS_EQUAL,
   OP_STAR_EQUAL,
   OP_SLASH_EQUAL,
   OP_PERCENT_EQUAL,
   OP_BANG_EQUAL,
   OP_AMPERSAND_EQUAL,
   OP_PIPE_EQUAL,
   OP_UP_CARET_EQUAL,
   OP_DOUBLE_LCHEVRON_EQUAL,
   OP_DOUBLE_RCHEVRON_EQUAL,
   OP_LBRACKET,
   OP_RBRACKET,
   OP_LPAREN,
   OP_RPAREN,
   OP_LBRACE,
   OP_RBRACE,
   OP_DOUBLE_AMPERSAND,
   OP_DOUBLE_PIPE,
   OP_LCHEVRON,
   OP_RCHEVRON,
   OP_LCHEVRON_EQUAL,
   OP_RCHEVRON_EQUAL,
   OP_EQUAL_EQUAL,
} Operator;

const char *operator_to_str(Operator op);

#endif // !FOX_OPERATOR_H_
